<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDrPdvPL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDrPdvPL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDrPdvPL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDrPdvPL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDrPdvPL\App_KernelDevDebugContainer([
    'container.build_hash' => 'DrPdvPL',
    'container.build_id' => '81c4334c',
    'container.build_time' => 1591173449,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDrPdvPL');
